lib/uro_web/router.ex
defmodule UroWeb.Router do
  use UroWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
  extensions: [PowResetPassword, PowEmailConfirmation]
  use PowAssent.Phoenix.Router

  @view_commands [:index, :show]
  @modify_commands [:new, :edit, :create, :update, :delete]

  pipeline :remote_ip do
    plug RemoteIp
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: UroWeb.AuthErrorHandler
    plug Uro.EnsureUserNotLockedPlug,
      error_handler: UroWeb.AuthErrorHandler
  end

  pipeline :protected_admin do
    plug Uro.Plug.RequireAdmin
  end

  pipeline :protected_avatar_upload do
    plug Uro.Plug.RequireAvatarUploadPermission
  end

  pipeline :protected_map_upload do
    plug Uro.Plug.RequireMapUploadPermission
  end

  pipeline :protected_prop_upload do
    plug Uro.Plug.RequirePropUploadPermission
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: UroWeb.AuthErrorHandler
    plug Uro.EnsureUserNotLockedPlug,
      error_handler: UroWeb.AuthErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug UroWeb.APIAuthPlug, otp_app: :uro
  end

  pipeline :api_protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: UroWeb.APIAuthErrorHandler
    plug Uro.EnsureUserNotLockedPlug,
      error_handler: UroWeb.APIAuthErrorHandler
  end

  pipeline :dashboard do
    #plug :put_layout, {UroWeb.LayoutView, "dashboard.html"}
  end

  #######
  # API #
  #######

  scope "/api/v1", UroWeb.API.V1, as: :api_v1 do
    pipe_through [:remote_ip, :api]

    resources "/registration", RegistrationController, singleton: true, only: [:create]
    resources "/session", SessionController, singleton: true, only: [:create, :delete]
    post "/session/renew", SessionController, :renew

    resources "/users", UserController, only: [:show]

    resources "/avatars", UserContent.AvatarController, only: [:show]
    resources "/maps", UserContent.MapController, only: [:show]

    resources "/shards", ShardController, only: [:index, :create, :update, :delete]

  end

  scope "/api/v1", UroWeb.API.V1, as: :api_v1 do
    pipe_through [:remote_ip, :api, :api_protected]

    # Your protected API endpoints here
    get "/profile", RegistrationController, :show, as: :profile
    resources "/identity_proofs", IdentityProofController, as: :identity_proof, only: [:show, :create]
  end

  scope "/api/v1/dashboard", UroWeb.API.V1, as: :api_v1_dashboard do
    pipe_through [:remote_ip, :api, :api_protected, :protected_avatar_upload]

    resources "/avatars", Dashboard.UserContent.AvatarController, as: :avatar, only: @modify_commands
  end

  scope "/api/v1/dashboard", UroWeb.API.V1, as: :api_v1_dashboard do
    pipe_through [:remote_ip, :api, :api_protected, :protected_map_upload]

    resources "/maps", Dashboard.UserContent.MapController, as: :map, only: @modify_commands
  end

  scope "/api/v1/dashboard", UroWeb.API.V1, as: :api_v1_dashboard do
    pipe_through [:api, :api_protected]

    resources "/avatars", Dashboard.UserContent.AvatarController, as: :avatar, only: @view_commands
    resources "/maps", Dashboard.UserContent.MapController, as: :map, only: @view_commands
  end

  ########################
  # Session/Registration #
  ########################

  scope "/", UroWeb do
    pipe_through [:browser, :not_authenticated]

    get "/sign-in", SessionController, :new, as: :signin
    post "/sign-in", SessionController, :create, as: :signin

    get "/sign-up", RegistrationController, :new, as: :signup
    post "/sign-up", RegistrationController, :create, as: :signup
  end

  scope "/", UroWeb do
    pipe_through [:browser, :protected]

    delete "/", SessionController, :delete, as: :signin
    post "/sign-out", SessionController, :delete, as: :signout

    get "/profile", RegistrationController, :show, as: :profile
    get "/profile/edit", RegistrationController, :edit, as: :profile
	  put "/profile/edit", RegistrationController, :update, as: :profile
    #delete "/profile", RegistrationController, :delete, as: :profile
  end

  #############
  # Dashboard #
  #############

  scope "/dashboard", UroWeb, as: :dashboard do
    pipe_through [:browser, :protected, :dashboard, :protected_avatar_upload]

    resources "/avatars", Dashboard.UserContent.AvatarController, as: :avatar, only: @modify_commands
  end

  scope "/dashboard", UroWeb, as: :dashboard do
    pipe_through [:browser, :protected, :dashboard, :protected_map_upload]

    resources "/maps", Dashboard.UserContent.MapController, as: :map, only: @modify_commands
  end

  scope "/dashboard", UroWeb, as: :dashboard do
    pipe_through [:browser, :protected, :dashboard]

    get "/", DashboardController, :index, as: :root
    resources "/avatars", Dashboard.UserContent.AvatarController, as: :avatar, only: @view_commands
    resources "/maps", Dashboard.UserContent.MapController, as: :map, only: @view_commands
  end

  #########
  # Admin #
  #########

  scope "/admin", UroWeb, as: :admin do
    pipe_through [:browser, :protected_admin]

    get "/", Admin.PageController, :index, as: :root

    resources "/avatars", Admin.AvatarController, as: :avatar
    resources "/maps", Admin.MapController, as: :map
    resources "/props", Admin.PropController, as: :prop
    resources "/shards", Admin.ShardController, as: :shard
    resources "/events", Admin.EventController, as: :event
    resources "/users", Admin.UserController, as: :user
    post "/users/:id/lock", Admin.UserController, :lock
  end

  ########
  # Root #
  ########

  scope "/", UroWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/download", PageController, :download

    post "/reset-password", ResetPasswordController, :create
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  scope "/" do
    pipe_through [:browser]

    pow_extension_routes()
    pow_assent_routes()
  end

  ###########
  # Swagger #
  ###########

  def swagger_info do
    %{
      info: %{
        version: "0.1",
        title: "Uro"
      }
    }
  end
end

lib/uro_web/views/layout_view.ex
defmodule UroWeb.LayoutView do
  use UroWeb, :view
end

lib/uro_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || Application.get_env(:uro, :title) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li>
              <ul class="session">
                <%= if UroWeb.Helpers.Auth.signed_in?(@conn) do %>
                  <li><%= gettext("Signed in as:%{username}", username: safe_to_string(link(UroWeb.Helpers.Auth.session_display_name(@conn), to: Routes.profile_path(@conn, :show)))) |> raw() %></li>
                  <ul class="session_buttons">
                    <li><%= link gettext("Sign Out"), to: Routes.signout_path(@conn, :delete), method: :post %></li>
                    <%= if UroWeb.Helpers.Admin.is_session_admin?(@conn) do %>
                      <li><%= link gettext("Admin Panel"), to: Routes.admin_root_path(@conn, :index) %></li>
                    <% end %>
                  </ul>
                <% else %>
                  <ul class="session_buttons">
                    <li><%= link gettext("Sign In"), to: Routes.signin_path(@conn, :new) %></li>
                    <li><%= link gettext("Register"), to: Routes.signup_path(@conn, :new)%></li>
                  </ul>
                <% end %>
              </ul>
            </li>
          </ul>
          <ul class="static_links">
            <li>
              <%= link gettext("About"), to: Routes.page_path(@conn, :about) %>
            </li>
            <li>
              <%= link gettext("Download"), to: Routes.page_path(@conn, :download) %>
            </li>
          </ul>
        </nav>
        <a href=<%=Routes.page_path(@conn, :index) %> class="vsk-logo">
          <img src="<%= Routes.static_path(@conn, "/images/v-sekai.png") %>" alt="V-Sekai Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/uro_web/templates/layout/dashboard.html.eex
<h1>Dashboard</h1>
<%= @inner_content %>

lib/uro_web/templates/layout/error.html.eex
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p><%= gettext("Oops, something went wrong! Please check the errors below.") %></p>
</div>
<% end %>

lib/uro_web/templates/layout/searchbar.html.eex
<%= form_for @conn, @action, [method: :get], fn f -> %>
<%= search_input f, :query %>
<%= submit gettext("Search") %>
<% end %>

lib/uro_web/templates/layout/user_content_form.html.eex
<%= label @current_form, :name, gettext("Name") %>
<%= text_input @current_form, :name %>
<%= error_tag @current_form, :name %>

<%= label @current_form, :description, gettext("Description") %>
<%= textarea @current_form, :description %>
<%= error_tag @current_form, :description %>

<%= label @current_form, :user_content_data, gettext("Asset File") %>
<%= file_input @current_form, :user_content_data %>
<%= error_tag @current_form, :user_content_data %>

<%= label @current_form, :user_content_preview, gettext("Thumbnail File") %>
<%= file_input @current_form, :user_content_preview %>
<%= error_tag @current_form, :user_content_preview %>

<div>
  <%= submit gettext("Save") %>
</div>

lib/uro_web/templates/layout/user_content_table.html.eex
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Preview</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user_content <- @user_content_list do %>
    <tr>
      <td><%= user_content.name %></td>
      <td><%= user_content.description %></td>
      <td><%= Uro.Uploaders.UserContentPreview.url({user_content.user_content_preview, user_content}) |> img_tag() %></td>

      <td>
        <span><%= link "Show", to: @path_function_with_item.(:show, user_content) %></span>
        <span><%= link "Edit", to: @path_function_with_item.(:edit, user_content) %></span>
        <span><%= link "Delete", to: @path_function_with_item.(:delete, user_content), method: :delete, data: [confirm: gettext("Are you sure?")] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link @new_user_content_string, to: @path_function.(:new) %></span>

lib/uro_web/templates/layout/user_privilege_ruleset.html.eex
<h2><%= gettext("Privileges")%></h2>
<%= inputs_for @current_form, :user_privilege_ruleset, [skip_hidden: true], fn p -> %>
<%= label p, :can_upload_avatars, gettext("Can Upload Avatars") %>
<%= checkbox p, :can_upload_avatars %>
<%= error_tag p, :can_upload_avatars %>

<%= label p, :can_upload_maps, gettext("Can Upload Maps") %>
<%= checkbox p, :can_upload_maps %>
<%= error_tag p, :can_upload_maps %>

<%= label p, :can_upload_props, gettext("Can Upload Props") %>
<%= checkbox p, :can_upload_props %>
<%= error_tag p, :can_upload_props %>
<% end %>